WITH RECURSIVE ECOLI_GENERATION AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, eg.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN ECOLI_GENERATION eg ON e.PARENT_ID = eg.ID
)

SELECT 
    COUNT(*) AS COUNT, 
    GENERATION
FROM 
    ECOLI_GENERATION
WHERE 
    ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY 
    GENERATION
ORDER BY 
    GENERATION ASC;