-- 코드를 작성해주세요
SELECT
    T2.ITEM_ID,
    T2.ITEM_NAME,
    T2.RARITY
FROM
    ITEM_INFO T1
INNER JOIN
    ITEM_TREE T_TREE ON T1.ITEM_ID = T_TREE.PARENT_ITEM_ID
INNER JOIN
    ITEM_INFO T2 ON T_TREE.ITEM_ID = T2.ITEM_ID
WHERE
    T1.RARITY = 'RARE'
ORDER BY
    T2.ITEM_ID DESC;