-- 코드를 입력하세요
SELECT
    DISTINCT(B.CAR_ID)
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
JOIN
    CAR_RENTAL_COMPANY_CAR AS A ON B.CAR_ID = A.CAR_ID
WHERE
    A.CAR_TYPE = '세단'
    AND
    B.START_DATE BETWEEN '2022-10-01' AND '2022-11-01'
ORDER BY
    B.CAR_ID DESC;